### ISSUE TITLE
ModuleNotFoundError: No module named 'psyplot.compat'

### ISSUE THREAD

**Issue by AnnikaLau** [psyplot/psyplot#62] opened 2024-05-06 12:40 UTC
I have the following psyplot packages installed together with python 3.9.16:
```
psy-maps                  1.5.0            py39hf3d152e_1    conda-forge
psy-reg                   1.4.0            py39hf3d152e_3    conda-forge
psy-simple                1.5.0            py39hf3d152e_1    conda-forge
psy-transect              0.1.0                    pypi_0    pypi
psyplot                   1.5.0            py39hf3d152e_1    conda-forge
```
When I run `import psyplot.project as psy`, I get the error:
```
WARNING:psyplot.config.rcsetup:Failed to import EntryPoint(name='plugin', value='psy_reg.plugin', group='psyplot')!
WARNING:psyplot:Could not import EntryPoint(name='plugin', value='psy_reg.plugin', group='psyplot')
Traceback (most recent call last):
  File "/project/g110/alauber/envs/psyplot/lib/python3.9/site-packages/psyplot/__init__.py", line 132, in get_versions
    mod = ep.load()
  File "/project/g110/alauber/envs/psyplot/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "/project/g110/alauber/envs/psyplot/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/envs/psyplot/lib/python3.9/site-packages/psy_reg/plugin.py", line 36, in <module>
    from psyplot.compat.pycompat import map, filter
ModuleNotFoundError: No module named 'psyplot.compat'

```

Best,
Annika

**Comment by Chilipp** [comment] 2024-05-06 12:49
dear @AnnikaLau. Thanks for reporting! The error is caused by the psy-reg package that is unfortunately not yet compatible with psyplot v1.5.0. You can either uninstall that package for the moment or disable it via environment variables (see https://psyplot.github.io/psyplot/plugins.html#how-to-exclude-plugins)

**Comment by AnnikaLau** [comment] 2024-05-22 08:05
Thank you for the hint!
Unfortunately, I need to install psy-transect at the same time, which requires `"psy-maps>=1.5.0"`.
How do I exclude the plugins within a Python script?

**Comment by Chilipp** [comment] 2024-05-22 08:09
hi @AnnikaLau. I do not understand, sorry. `psy-reg` is causing the problem here, not `psy-maps`. can you just avoid installing `psy-reg`? if you necessarily need to use `psy-transect` and `psy-reg` at the same time at the moment, then you need to wait until `psy-reg` is compatible with v1.5.0 of psyplot (I can take care of this in June)

**Comment by Chilipp** [comment] 2024-05-22 11:58
alright, I understand. I recommend that you put the [psy-reg repo](https://github.com/psyplot/psy-reg/) under watch for releases (see screenshot)

![image](https://github.com/psyplot/psyplot/assets/9960249/90fbbe95-e15e-4fa0-848b-efc77cbb6ed7)

just in case that I forget to mention it here explicitly.

**Comment by AnnikaLau** [comment] 2024-05-22 12:00
Great, thank you!

**Comment by Chilipp** [comment] 2024-07-16 14:07
psy-reg has been updated and v1.5.0 has been published to PyPi. I'll close this issue when the package on conda-forge has been updated

**Comment by Chilipp** [comment] 2024-07-17 07:42
FYI: the PR of psy-reg v1.5.0 (https://github.com/conda-forge/psy-reg-feedstock/pull/19) has been merged, so it should be available soon via the conda-forge channel. I am closing this, but feel free to reopen it, when there are any other issues

**Closed as completed by Chilipp** 2024-07-17 07:42 UTC
